nelmio_cors:
    defaults:
        allow_origin: ['https://skywon01.github.io']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/taches': ~
